### ISSUE TITLE
使用shoushouway的一些插件模组冲突

### ISSUE THREAD

**Issue by LinzerHP** [WhiteXero/ShowIt#2]
shoushouway插件和假人共存的时候。召唤假人会展示手中物品，
使用whereis插件的时候会也会有类似现象，
这样刷屏很影响体验。
<img width="594" alt="Snipaste_2023-07-19_23-04-29" src="https://github.com/WhiteXero/ShowShowWay/assets/102501091/71e22c09-3a9b-48bd-80eb-e7f7df581d8f">
<img width="620" alt="Snipaste_2023-07-19_23-06-55" src="https://github.com/WhiteXero/ShowShowWay/assets/102501091/32d81169-b525-4408-b2e2-4f5706e2025b">

**Comment by WorldHim** [comment]
因为在使用 `!!here` 与 `!!vris` 时，服务器后台会输出 `*** has the following entity data:`，刚好在插件判断逻辑中会将 `entity data:` 冒号后的数据作为物品nbt来处理，然后触发展示机制。。

**Comment by WorldHim** [comment]
因为物品nbt以 `{` 开头，可以简单粗暴的在 `__init__.py` 第 26 行后面添加一个判断 `if nbt[0]=='{':`，然后补全下一行缩进。

**Comment by 3341232786** [comment]
> 因为物品nbt以 `{` 开头，可以简单粗暴的在 `__init__.py` 第 26 行后面添加一个判断 `if nbt[0]=='{':`，然后补全下一行缩进。

小白，同问题，已经打开py了没理解怎么添加，可以描述一下添加到哪里然后怎么做么

**Comment by WhiteXero** [comment]
修了！
